project_id = "zyziolikudoczsthyoja"

[functions.summarize-note]
verify_jwt = false

[functions.trading-assistant]
verify_jwt = false

[functions.embed-note]
verify_jwt = false

[functions.ask-ai]
verify_jwt = false

[functions.analyze-document]
verify_jwt = false

[functions.folder-insights]
verify_jwt = false

[functions.index-workflow-files]
verify_jwt = false

[functions.analyze-document-webhook]
verify_jwt = false

[functions.send-to-supermemory]
verify_jwt = false
